In [2]:
import pandas as pd
import numpy as np
import json

In [95]:
data = pd.read_csv("selected_tracks.csv")
songs = np.asarray(data['Track Name'])
data.columns

Index(['Position', 'Track Name', 'Artist', 'Streams', 'URL', 'danceability',
       'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'type', 'id', 'uri',
       'track_href', 'analysis_url', 'duration_ms', 'time_signature',
       'lyrics'],
      dtype='object')

In [77]:
#getting scores for danceability
danceability = np.asarray(data['danceability'])
daceablity_scale = danceability/0.5 #scaling it according to basline for the height of the jagged line
daceablity_scale

array([1.864, 0.702, 1.414, 0.734, 1.028, 1.408, 1.588, 1.792, 1.606,
       1.352, 1.308, 1.51 , 0.76 , 1.282])

In [26]:
#getting opacity percentage for energy
energy = np.asarray(data['energy'])
opacity_baseline = 0.3
adjusted_opacity = energy+opacity_baseline #setting opacity of entire picture
adjusted_opacity

array([1.007, 0.596, 1.255, 0.411, 1.03 , 0.525, 1.093, 0.886, 1.015,
       0.909, 0.93 , 0.917, 0.519, 1.157])

In [142]:
#getting cloud level for speechiness
speechiness = np.asarray(data['speechiness'])
cloud_level = np.zeros(len(speechiness)) #determining how much cloud to display
for i in range(len(speechiness)):
    if speechiness[i]<=0.33:
        cloud_level[i] = 1
    elif 0.33<speechiness[i]<=0.66:
        cloud_level[i] = 2
    else:
        cloud_level[i] = 3
cloud_level

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.])

In [84]:
#getting number of lines for acousticness, if under 0.1 then 0 lines
acousticness = np.asarray(data['acousticness'])
number_of_lines = np.zeros(len(acousticness))
for i in range(len(acousticness)):
    number_dec = str(acousticness[i]-int(acousticness[i])).split('.')[1][0]
    number_of_lines[i] = int(number_dec)
number_of_lines = 10-number_of_lines
number_of_lines

array([ 9.,  1.,  9.,  1., 10.,  1., 10.,  9.,  8., 10.,  9., 10.,  1.,
       10.])

In [177]:
#getting radius for instrumentalness
instrumentalness = np.asarray(data['instrumentalness'])
max_radius = 150 #diamiter when instrumentalness is 0
min_radius = 2 #diamiter when instrumentalness is 1
radius = (1-instrumentalness)*max_radius #getting radius to determine the size of the sun/moon
radius

array([150.      , 150.      , 150.      , 149.994045, 149.98569 ,
        51.45    , 150.      , 150.      , 149.9799  , 150.      ,
       150.      , 150.      , 148.44    , 149.199   ])

In [99]:
#getting scale for liveness
liveness = np.asarray(data['liveness'])
liveness

array([0.345 , 0.095 , 0.202 , 0.0897, 0.0897, 0.106 , 0.0952, 0.79  ,
       0.0574, 0.152 , 0.111 , 0.0625, 0.0827, 0.0695])

In [98]:
liveness_scale = liveness/0.5 #scale for the green mountains based on baseline
liveness_scale

array([0.69  , 0.19  , 0.404 , 0.1794, 0.1794, 0.212 , 0.1904, 1.58  ,
       0.1148, 0.304 , 0.222 , 0.125 , 0.1654, 0.139 ])

In [122]:
#getting color gradient for valence
valence = np.asarray(data['valence'])
valence_adjusted = valence*100

In [133]:
offsets = 100-np.absolute(50-valence*100)
offsets

array([73.1 , 62.  , 92.5 , 69.8 , 83.4 , 74.3 , 82.3 , 85.8 , 92.6 ,
       99.2 , 93.  , 75.5 , 55.17, 53.9 ])

In [139]:
#getting set of waves for tempo
tempo = np.asarray(data['tempo'])
tempo

array([119.988, 115.284, 125.989,  82.642, 171.005, 120.006, 123.941,
       116.971, 101.085, 142.037,  89.991, 193.896,  73.537, 122.728])

In [138]:
number_of_waves = np.zeros(len(tempo))
for i in range(len(tempo)):
    if tempo[i]<=60:
        number_of_waves[i] = 1
    elif 60<tempo[i]<=120:
        number_of_waves[i] = 2
    elif 120<tempo[i]<=180:
        number_of_waves[i] = 4
    else:
        number_of_waves[i] = 4
number_of_waves

array([2., 2., 4., 2., 4., 4., 4., 2., 2., 4., 2., 4., 2., 4.])

In [140]:
#getting mode
mode = np.asarray(data['mode'])
mode

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [178]:
d = {'songs': songs,'daceablity_scale': daceablity_scale,'adjusted_opacity': adjusted_opacity,
     'cloud_level': cloud_level,'number_of_lines': number_of_lines,'radius': radius,'liveness_scale': liveness_scale,
     'offsets': offsets,'number_of_waves': number_of_waves,'mode': mode}

In [179]:
df = pd.DataFrame(data=d)

In [180]:
df

songs  daceablity_scale  adjusted_opacity  \
0                   Broke In A Minute             1.864             1.007   
1                lovely (with Khalid)             0.702             0.596   
2                          Boss Bitch             1.414             1.255   
3               when the party's over             0.734             0.411   
4                     Blinding Lights             1.028             1.030   
5                 everything i wanted             1.408             0.525   
6                     Don't Start Now             1.588             1.093   
7                             The Box             1.792             0.886   
8                                Tusa             1.606             1.015   
9          Life Is Good (feat. Drake)             1.352             0.909   
10  10,000 Hours (with Justin Bieber)             1.308             0.930   
11                             Tattoo             1.510             0.917   
12                     No Time To Die             0.760             0.519   
13                           Amarillo             1.282             1.157   

    cloud_level  number_of_lines      radius  liveness_scale  offsets  \
0           1.0              9.0  150.000000          0.6900    73.10   
1           1.0              1.0  150.000000          0.1900    62.00   
2           1.0              9.0  150.000000          0.4040    92.50   
3           1.0              1.0  149.994045          0.1794    69.80   
4           1.0             10.0  149.985690          0.1794    83.40   
5           1.0              1.0   51.450000          0.2120    74.30   
6           1.0             10.0  150.000000          0.1904    82.30   
7           1.0              9.0  150.000000          1.5800    85.80   
8           1.0              8.0  149.979900          0.1148    92.60   
9           2.0             10.0  150.000000          0.3040    99.20   
10          1.0              9.0  150.000000          0.2220    93.00   
11          1.0             10.0  150.000000          0.1250    75.50   
12          1.0              1.0  148.440000          0.1654    55.17   
13          1.0             10.0  149.199000          0.1390    53.90   

    number_of_waves  mode  
0               2.0     0  
1               2.0     0  
2               4.0     0  
3               2.0     1  
4               4.0     1  
5               4.0     0  
6               4.0     0  
7               2.0     0  
8               2.0     1  
9               4.0     0  
10              2.0     1  
11              4.0     1  
12              2.0     0  
13              4.0     0

In [168]:
df.to_csv (r'C:\Users\yuexitwang\music_features.csv', index = False)